---
- name: Start photoprism
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ photoprism_user_id }}"
        group: "{{ photoprism_group_id }}"
        mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
      with_items:
        - "{{ photoprism_data_directory }}"
        - "{{ photoprism_original_directory }}"
        - "{{ photoprism_cache_directory }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ photoprism_compose_file }}"

    - name: Start photoprism
      community.docker.docker_compose_v2:
        project_src: "{{ photoprism_data_directory }}"
        state: present        
  when: photoprism_enabled is true

- name: Stop photoprism
  block:
    - name: Stop photoprism
      community.docker.docker_container:
        name: "{{ photoprism_container_name }}"
        state: absent
  when: photoprism_enabled is false