---
# enable or disable the application
nextcloud_enabled: false

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"
nextcloud_config_directory: "{{ nextcloud_data_directory }}/configs"

# network
nextcloud_hostname: "nextcloud"
nextcloud_port: "1056"
nextcloud_user_id: "{{ default_owner }}"
nextcloud_group_id: "{{ default_group }}"
nextcloud_network_name: docker_network
nextcloud_available_externally: false

# docker
nextcloud_compose_file: "{{ nextcloud_data_directory }}/docker-compose.yaml"
nextcloud_container_name: "nextcloud"
nextcloud_image_name: "nextcloud"
nextcloud_image_version: "latest"

# specs
nextcloud_memory: "2g"
nextcloud_cpu: 2

# database
mysql_nextcloud_db: "nextcloud_db"
nextcloud_db_username: nextcloud_user