---
- name: Start grafana
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ monitoring_user_id }}"
        group: "{{ monitoring_group_id }}"
        mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
      with_items:
        - "{{ grafana_data_directory }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ grafana_compose_file }}"

    - name: Start grafana
      community.docker.docker_compose_v2:
        project_src: "{{ grafana_data_directory }}"
        state: present        
  when: grafana_enabled is true

- name: Stop grafana
  block:
    - name: Stop grafana
      community.docker.docker_container:
        name: "{{ grafana_container_name }}"
        state: absent
  when: grafana_enabled is false