---
- name: Start grafana
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ grafana_data_directory }}"
        state: directory
        owner: "{{ monitoring_user_id }}"
        group: "{{ monitoring_group_id }}"
        mode: '{{ (ansible_facts[grafana_data_directory].stat.mode | default(omit)) | default("0755", true) }}'

    - name: Debug ansible user
      debug:
        msg:
          - "ansible_user: {{ ansible_user | default('undefined') }}"
          - "ansible_ssh_user: {{ ansible_ssh_user | default('undefined') }}"
          - "monitoring_user_id: {{ monitoring_user_id }}"
          - "monitoring_group_id: {{ monitoring_group_id }}"

    - name: Get ownership of grafana_data_directory
      stat:
        path: "{{ grafana_data_directory }}"
      register: grafana_data_dir_stat

    - name: Debug ownership of grafana_data_directory
      debug:
        msg:
          - "owner: {{ grafana_data_dir_stat.stat.pw_name | default('unknown') }}"
          - "group: {{ grafana_data_dir_stat.stat.gr_name | default('unknown') }}"
          - "mode: {{ grafana_data_dir_stat.stat.mode | default('unknown') }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ grafana_compose_file }}"

    - name: Start grafana
      community.docker.docker_compose_v2:
        project_src: "{{ grafana_data_directory }}"
        state: present        
  when: grafana_enabled is true

- name: Stop Grafana if not enabled
  when: not grafana_enabled | bool
  block:
    - name: Gather Grafana container info (do not fail if missing)
      community.docker.docker_container_info:
        name: grafana
      register: container_info
      failed_when: false

    - name: Stop Grafana container if running
      community.docker.docker_compose_v2:
        project_src: "{{ grafana_data_directory }}"
        state: absent
      when:
        - container_info.container is defined
        - (container_info.container.State.Running | default(false)) | bool
