---
duplicati_enabled: false
duplicati_available_externally: false

# directories
duplicati_directory: "{{ docker_home }}/duplicati"
duplicati_data_directory: "{{ duplicati_directory }}/config"
duplicati_compose_file: "{{ duplicati_directory }}/docker-compose.yaml"

# permissions
duplicati_data_permissions: "ro" # set this to rw to enable the ability to restore data

# uid / gid
duplicati_user_id: "{{ default_owner }}"
duplicati_group_id: "{{ default_group }}"

# network
duplicati_port: "8200"
duplicati_hostname: "duplicati"
duplicati_network_name: docker_network

duplicati_memory: 1g

# docker
duplicati_container_name: duplicati