---
transmission_enabled: false
transmission_user_id: "1000"
transmission_group_id: "1000"
transmission_user: root

# directories
transmission_directory: "{{ docker_home }}/media/transmission"
transmission_compose_file: "{{ transmission_directory }}/docker-compose.yaml"
transmission_config_directory: "{{ transmission_directory }}/config"
transmission_upload_directory: "{{ transmission_directory }}/uploads"
transmission_plugins_directory: "{{ transmission_directory }}/plugins"

# network
transmission_port: "9091"
transmission_hostname: "transmission"

# docker
transmission_container_name: transmission
transmission_image_version: latest
transmission_network_name: docker_network
transmission_memory: 500M
transmission_cpus: 1