---
homeassistant_enabled: false
homeassistant_user_id: 1000
homeassistant_group_id: 1000
homeassistant_available_by_traefik: false

# directories
homeassistant_data_directory: "{{ docker_home }}/homeassistant"
homeassistant_config_directory: "{{ homeassistant_data_directory }}/config"
homeassistant_compose_file: "{{ homeassistant_data_directory }}/docker-compose.yaml"
# network
homeassistant_port: "8123"
homeassistant_hostname: "homeassistant"
homeassistant_network_name: docker_network

# docker
homeassistant_container_name: "homeassistant"
homeassistant_image_name: "homeassistant/home-assistant"
homeassistant_image_version: latest

# specs
homeassistant_memory: 1g