---
- name: Setup Adguard 
  when: adguard_enabled is true
  block:
  - name: Ensure directories exist
    become: true
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ adguard_user_id }}"
      group: "{{ adguard_group_id }}"
      mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
    with_items:
      - "{{ adguard_directory }}"

  - name: Copy Docker Compose template
    template:
      src: docker-compose.yaml.j2
      dest: "{{ adguard_compose_file }}"

  - name: Start adguard
    community.docker.docker_compose_v2:
      project_src: "{{ adguard_directory }}"
      state: present

- name: Stop adguard if not enabled
  when: not adguard_enabled | bool
  block:
    - name: Gather adguard container info (do not fail if missing)
      community.docker.docker_container_info:
        name: adguard
      register: container_info
      failed_when: false

    - name: Stop adguard container if running
      community.docker.docker_compose_v2:
        project_src: "{{ adguard_directory }}"
        state: absent
      when:
        - container_info.container is defined
        - (container_info.container.State.Running | default(false)) | bool
