---
- name: Nassible
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - role: geerlingguy.docker
      vars:
        docker_apt_filename: download_docker_com_linux_ubuntu
    - role: docker
    - role: calibre
    - role: adguard
    - role: transmission
    - role: homepage
    - role: prometheus
    - role: grafana
    - role: radarr
    - role: jackett