---
- name: Start booklore
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ booklore_user_id }}"
        group: "{{ booklore_group_id }}"
        mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
      with_items:
        - "{{ booklore_data_directory }}"
        - "{{ booklore_upload_directory }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ booklore_compose_file }}"

    - name: Start booklore
      community.docker.docker_compose_v2:
        project_src: "{{ booklore_data_directory }}"
        state: present        
  when: booklore_enabled is true

- name: Stop booklore
  block:
    - name: Stop booklore
      community.docker.docker_container:
        name: "{{ booklore_container_name }}"
        state: absent
  when: booklore_enabled is false