---
- name: Start sonarr
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ sonarr_user_id }}"
        group: "{{ sonarr_group_id }}"
        mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
      with_items:
        - "{{ sonarr_data_directory }}"
        - "{{ sonarr_config_directory }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ sonarr_compose_file }}"

    - name: Start sonarr
      community.docker.docker_compose_v2:
        project_src: "{{ sonarr_data_directory }}"
        state: present        
  when: sonarr_enabled is true

- name: Stop sonarr
  block:
    - name: Stop sonarr
      community.docker.docker_container:
        name: "{{ sonarr_container_name }}"
        state: absent
  when: sonarr_enabled is false