---
homepage_user_id: 1000
homepage_group_id: 1000
# enable or disable the application
homepage_enabled: false
homepage_available_by_traefik: false

# directories
homepage_data_directory: "{{ docker_home }}/homepage"
homepage_compose_file: "{{ homepage_data_directory }}/docker-compose.yaml"
# network
homepage_hostname: "homepage"
homepage_port: "11111"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"
homepage_network_name: docker_network

# specs
homepage_memory: "250m"
homepage_cpu: 1


# settings
homepage_title: NASsible Homepage
homepage_locale: en-GB

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  language: "{{ homepage_locale }}"
  showStats: true

homepage_services_yaml:
  - Networking:
      - Router:
          icon: asus-router
          href: http://192.168.1.1/
          description: Asus Router

homepage_widgets_yaml:
  - search:
      provider: google # google, duckduckgo, bing, baidu, brave or custom
      focus: true # Optional, will set focus to the search bar on page load
      target: _blank # One of _self, _blank, _parent or _top
  - greeting:
      text_size: xl
      text: NASsible
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms

homepage_bookmarks_yaml:
  - Developer:
      - "Ansible-NAS":
          - abbr: AN
            href: https://ansible-nas.io/
      - Github:
          - abbr: GH
            href: https://github.com/
            icon: github
      - "Hacker News":
          - abbr: HN
            href: https://news.ycombinator.com/
  - Social:
      - Reddit:
          - abbr: RE
            href: https://reddit.com/
            icon: reddit
  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/
            icon: youtube