##### General #####
# Hostname of your server
hostname: home_server
# Default owner and group IDs for created files
default_owner: 1000
default_group: 1000
# Timezone for services
timezone: Europe/Budapest

##### Enable / Disable features #####
mariadb_enabled: true
cloudflare_enabled: true
duckdns_enabled: true
grafana_enabled: true
homeassistant_available_by_traefik: true
homepage_available_by_traefik: true
jackett_enabled: true
jellyfin_enabled: true
nextcloud_enabled: true
photoprism_enabled: true
radarr_enabled: true
torrents_enabled: true
traefik_enabled: true

##### Paths #####
# Where docker compose files and configs are stored
# Please give attention if you have more partitions
# (Override as needed for your environment)
docker_home: "{{ ansible_env.HOME }}/services"
# Where the persistent and user data is stored
data_directory: /mnt
downloads_folder: "{{ data_directory }}/downloads"
torrents_root: "{{ downloads_folder }}/torrents"
books_root: "{{ data_directory }}/calibre"
comics_root: "{{ data_directory }}/calibre/comics"
backup_root: "{{ data_directory }}/backups"
nextcloud_root: "{{ data_directory }}/nextcloud"
movies_root: "{{ downloads_folder }}/videos"
series_root: "{{ downloads_folder }}/series"

##### Calibre #####
calibre_directory: "{{ docker_home }}/media/calibre"
calibre_upload_directory: "{{ downloads_folder }}/book-upload"
calibre_books_directory: "{{ books_root }}/books"
calibre_comics_directory: "{{ comics_root }}"
calibre_network_name: docker_network
calibre_image_version: 6.28.0

##### Adguard #####
adguard_network_name: docker_network
adguard_webserver_port: 3001

##### Transmission #####
transmission_network_name: docker_network
transmission_user: abc
transmission_book_download_folder_for_calibre: books
calibre_upload_folder: calibre_uploads

##### Homepage #####
homepage_network_name: docker_network

##### Monitoring #####
prometheus_network_name: monitoring
grafana_network_name: monitoring

##### Radarr #####
# radarr_extra_volumes:
#   - /path/to/host/folder1:/container/folder1  # Example: /mnt/data/movies:/movies
#   - /path/to/host/folder2:/container/folder2  # Example: /mnt/data/series:/series

##### Jellyfin #####
jellyfin_user_id: "{{ default_owner }}"
jellyfin_group_id: "{{ default_owner }}"
# jellyfin_extra_volumes:
#   - /path/to/host/folder1:/container/folder1  # Example: /mnt/data/media:/media
#   - /path/to/host/folder2:/container/folder2  # Example: /mnt/data/music:/music

##### DuckDNS #####
duckdns_user_id: "{{ default_owner }}"
duckdns_group_id: "{{ default_owner }}"
duckdns_subdomains: duckdns_subdomain

##### Traefik #####
ansible_nas_domain: example.com
ansible_nas_email: duckdns_email

