##### General #####
hostname: sample-host

# timezone for services
timezone: Europe/Budapest

# docker_home is the place where the docker composes and configs can be found
docker_home: /mnt/services/docker

# data_directory is the place where any data for example books, downloads, shares
data_directory: /mnt/data
books_root: "{{ data_directory }}/books"
comics_root: "{{ data_directory }}/comics"
nextcloud_root: "{{ data_directory }}/nextcloud"

##### Calibre #####
# calibre_enabled: install & run calibre or not
calibre_enabled: true
# calibre_directory: where the compose file can be found
calibre_directory: "{{ docker_home }}/media/calibre"
# calibre_upload_directory: if you copy anything in uploads it will automatically handle
calibre_upload_directory: "{{ calibre_directory }}/uploads"
calibre_books_directory: "{{ books_root }}"
calibre_comics_directory: "{{ comics_root }}"

calibre_network_name: docker_network
calibre_image_version: latest

##### Adguard #####
adguard_enabled: true
adguard_network_name: docker_network
adguard_webserver_port: 3001

##### Transmission #####
transmission_enabled: true
transmission_network_name: docker_network
transmission_book_download_folder_for_calibre: books
calibre_upload_folder: calibre_uploads

##### Homepage #####
homepage_enabled: true
homepage_network_name: docker_network

##### Prometheus #####
prometheus_enabled: true
prometheus_network_name: monitoring

##### Grafana #####
grafana_enabled: true
grafana_network_name: monitoring

##### Radarr #####
radarr_enabled: true


##### Jackett #####
jackett_enabled: true

##### TBD #####
torrents_root: "{{ data_directory }}/torrents"
downloads_folder: "{{ data_directory }}/downloads"


#### JellyFin #####
jellyfin_enabled: true
#jellyfin_user_id: 1000
#jellyfin_group_id: 1003

#### DuckDNS ####
duckdns_enabled: true
#duckdns_user_id: 1000
#duckdns_group_id: 1003
#duckdns_subdomains: todo

#### MariaDB ####
mariadb_enabled: true


#### Photoprism ####
photoprism_enabled: true

#### Nextcloud ####
nextcloud_enabled: true


#### Traefik ####
traefik_enabled: true
#ansible_nas_domain: todo
# ansible_nas_email: yourmail

homepage_available_by_traefik: false
homeassistant_available_by_traefik: false