---
- name: Start Prometheus
  block:
    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user_id }}"
        group: "{{ prometheus_group_id }}"
        mode: '{{ (ansible_facts[item].stat.mode | default(omit)) | default("0755", true) }}'
      with_items:
        - "{{ prometheus_data_directory }}"

    - name: Copy Docker Compose template
      template:
        src: docker-compose.yaml.j2
        dest: "{{ prometheus_compose_file }}"

    - name: Copy Docker Compose template
      template:
        src: prometheus.yaml.j2
        dest: "{{ prometheus_config_file }}"

    - name: Start Prometheus
      community.docker.docker_compose_v2:
        project_src: "{{ prometheus_data_directory }}"
        state: present        
  when: prometheus_enabled is true

- name: Stop Prometheus
  block:
    - name: Stop Prometheus
      community.docker.docker_container:
        name: "{{ prometheus_container_name }}"
        state: absent
  when: prometheus_enabled is false